# Inteligencia Artificial

## Capítulo 2
### Nombre: Patricio Quishpe
### Matemática Básica para Ciencias de Datos

- **Unidad 1.** Introducción
- **Unidad 2.** Matemática Básica para Ciencias de Datos
- **Unidad 3.** Entendiendo las Ciencias de Datos: Vector
- **Unidad 4.** Entendiendo las Ciencias de Datos: Matriz
- **Unidad 5.** Entendiendo las Ciencias de Datos: Derivativas

# Quiz

___

## Q 02-01

### Cree ejemplos de vector cero, vector unitario, matriz cuadrada, matriz diagonal, matriz identidad y matriz simétrica uno por uno, y represente vectores y matrices con NumPy.

In [4]:
import numpy as np

# Vector con todos sus elementos iguales a 0
vector_cero = np.zeros(5)
print("Vector Cero:\n", vector_cero, "\n")

# Vector con todos sus elementos iguales a 1
vector_unitario = np.ones(5)
print("Vector Unitario:\n", vector_unitario, "\n")

# Matriz con igual número de filas y columnas
matriz_cuadrada = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])
print("Matriz Cuadrada:\n", matriz_cuadrada, "\n")

# Solo tiene valores distintos de cero en la diagonal principal
matriz_diagonal = np.diag([3, 5, 7])
print("Matriz Diagonal:\n", matriz_diagonal, "\n")

# Diagonal principal con 1 y el resto 0
matriz_identidad = np.eye(3)
print("Matriz Identidad:\n", matriz_identidad, "\n")

# Igual a su traspuesta (A = A^T)
matriz_simetrica = np.array([[2, 3, 4],
                             [3, 5, 6],
                             [4, 6, 7]])
print("Matriz Simétrica:\n", matriz_simetrica, "\n")

# Verificación de simetría
print("¿Es simétrica?:", np.array_equal(matriz_simetrica, matriz_simetrica.T))


Vector Cero:
 [0. 0. 0. 0. 0.] 

Vector Unitario:
 [1. 1. 1. 1. 1.] 

Matriz Cuadrada:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Matriz Diagonal:
 [[3 0 0]
 [0 5 0]
 [0 0 7]] 

Matriz Identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Matriz Simétrica:
 [[2 3 4]
 [3 5 6]
 [4 6 7]] 

¿Es simétrica?: True


___

## Q 02-02

### Las acciones de tres empresas A, B y C son 1 millón de wones, 800.000 wones y 500.000 wones, respectivamente. Queremos encontrar la cantidad necesaria para comprar 3, 4 y 5 acciones de estas acciones, respectivamente.

1) Exprese el precio y la cantidad de las acciones como vector p y vector n, respectivamente y codificados con NumPy.

In [ ]:
import numpy as np

# A = 1,000,000 | B = 800,000 | C = 500,000
p = np.array([1000000, 800000, 500000])
print("Vector de precios p:\n", p, "\n")
# A = 3 | B = 4 | C = 5
n = np.array([3, 4, 5])
print("Vector de cantidades n:\n", n, "\n")

print("Precio total :", np.dot(p, n))

print("\nPrecio total :", np.sum(p * n))

Vector de precios p:
 [1000000  800000  500000] 

Vector de cantidades n:
 [3 4 5] 

Precio total de las compras: 8700000

Precio total de las compras: 8700000


2) La cantidad necesaria para comprar acciones se expresa mediante multiplicación y el valor se calcula mediante la operación Numpy.

In [9]:

print("Precio total :", np.dot(p, n))

print("\nPrecio total :", np.sum(p * n))

Precio total : 8700000

Precio total : 8700000


___

## Q 02-03

### Cuando se ejecuta el siguiente código, todos los datos de la imagen numérica MNIST se convierten en vectores para crear una única matriz NumPy X. Utilice esta matriz para resolver el siguiente problema.
```
from sklearn.datasets import load_digits
X=load_digits().data
```

1) Encuentre la similitud entre la primera imagen y la décima imagen usando el producto escalar.


imagen_1 = X[0]
imagen_10 = X[9] # La décima imagen

similitud = np.dot(imagen_1 , imagen_10 = X[9]) 

print(f"Similitud (Producto Escalar): {similitud}")

2) Encuentre la similitud para una combinación de todas las imágenes usando el producto escalar, ¿cómo sería eficiente implementarlo (pista: usando matrices y multiplicación de matrices)?


print(f"Similitud (Producto Escalar): {similitud}")

___

## Q 02-04

### Calculate the following inverse matrix.


![matrix.png](attachment:matrix.png)

In [10]:
import numpy as np

# Matriz cuadrada 2x2
A = np.array([[4, 7],
              [2, 6]])
print("Matriz A:\n", A)
# Calcular el determinante
det = np.linalg.det(A)
print("Determinante:", det)
# Calcular la inversa
A_inv = np.linalg.inv(A)
print("Matriz inversa de A:\n", A_inv)


Matriz A:
 [[4 7]
 [2 6]]
Determinante: 10.000000000000002
Matriz inversa de A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


___

## Q 02-05

### El problema del precio de la vivienda en Boston es un problema de predicción del precio de la vivienda en cada ciudad de Boston (EE.UU.) utilizando características como el índice de delincuencia y la contaminación atmosférica de la zona. Puede importarse del paquete scikit-learn. Encuentre el vector de pesos x cuando el problema del precio de la vivienda en Boston se resuelva con el modelo de predicción lineal Ax=b. Los datos matriciales y vectoriales pueden obtenerse como sigue. Aquí, para simplificar el problema, limitamos los datos de entrada a la tasa de criminalidad (CRIM), la calidad del aire (NOX), el número de habitaciones (RM) y la edad (AGE), y sólo se utilizaron cuatro datos.

Ejecute el código siguiente para comprobar si la magnitud o el signo del vector de pesos obtenido al ejecutar el programa se ajusta a la noción común. Para ello, interprete la salida impresa para todos los factores: CRIM, NOX, RM y EDAD.

(※ Escriba la salida interpretada como "el precio de la vivienda está en proporción inversa a la tasa de criminalidad (CRIM)").
```
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
boston = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)
X = np.hstack([boston.values[::2, :], boston.values[1::2, :2]])
y = boston.values[1::2, 2]
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]
```

In [12]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
boston = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)
X = np.hstack([boston.values[::2, :], boston.values[1::2, :2]])
y = boston.values[1::2, 2]
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]
print("Matriz A:\n", A)
print("\nVector b:\n", b)

Matriz A:
 [[6.320e-03 5.380e-01 6.575e+00 6.520e+01]
 [2.731e-02 4.690e-01 6.421e+00 7.890e+01]
 [2.729e-02 4.690e-01 7.185e+00 6.110e+01]
 [3.237e-02 4.580e-01 6.998e+00 4.580e+01]]

Vector b:
 [24.  21.6 34.7 33.4]


___

## Fin